/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.gui.ders10;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class FrmAnasayfa extends javax.swing.JFrame {

    public static List<Kisi> kisiListe=new ArrayList<>();

    /**
     * Creates new form FrmAnasayfa
     */
    FileUtils fu= new FileUtils();
            
    public FrmAnasayfa() {
        initComponents();
        fu.readFile();
        tabloyuDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListe = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuKisiEkle = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListe);

        jMenu1.setText("Dosya");

        mnuKisiEkle.setText("Kişi Ekle");
        mnuKisiEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKisiEkleActionPerformed(evt);
            }
        });
        jMenu1.add(mnuKisiEkle);

        jMenuItem1.setText("Çıkış");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hakkında");

        jMenuItem2.setText("Hakkında");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Vektörel Java Ders 10", "Hakkında", 2);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuKisiEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKisiEkleActionPerformed
        FrmKisi ekle=new FrmKisi(this, true);
        ekle.setLocationRelativeTo(null);
        ekle.show();
        tabloyuDoldur();
    }//GEN-LAST:event_mnuKisiEkleActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     fu.writeToFile();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuKisiEkle;
    private javax.swing.JTable tblListe;
    // End of variables declaration//GEN-END:variables

    /**
     * Custom methods
     */
    private void tabloyuDoldur() {
        String[] columnNames = new String[3];
        columnNames[0] = "No";
        columnNames[1] = "Ad";
        columnNames[2] = "Soyad";
        
        Object[][] data = new Object[kisiListe.size()][3];
        for (int i = 0; i < kisiListe.size(); i++) {
            data[i][0] = kisiListe.get(i).getNo();
            data[i][1] = kisiListe.get(i).getAd();
            data[i][2] = kisiListe.get(i).getSoyad();
        }        

        tblListe.setModel(new DefaultTableModel(data, columnNames));
        tblListe.setDefaultEditor(Object.class, null);
    }

}
